codecov:
  require_ci_to_pass: false

ignore:
  - "**/integration/"
  - "**/examples/"
  - "**/benches/"
  - "src/tests.rs"
  - "src/error.rs"
  - "src/swmr/generic/traits/container_impls/"
  - "src/swmr/generic/traits/container_impls.rs"
  - "src/swmr/generic/traits/type_impls/"
  - "src/swmr/generic/traits/type_impls.rs"
  - "src/swmr/generic/tests.rs"
  - "src/swmr/generic/tests/"
  - "src/swmr/wal/tests.rs"
  - "src/swmr/wal/tests/"
  - "src/wal/impls.rs"
  - "src/unsync/tests.rs"
  - "src/unsync/tests/"

coverage:
  status:
    project: # Overall project status
      default:
        target: auto
        if_not_found: success
        only_pulls: false
    patch: # Status for the patch in pull requests
      default:
        target: auto
        if_not_found: success
        only_pulls: true
    changes: false # Whether to comment on the coverage changes in pull requests

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
