[package]
name = "orderwal"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/orderwal"
homepage = "https://github.com/al8n/orderwal"
documentation = "https://docs.rs/orderwal"
description = "An ordered Write-Ahead Log implementation for Rust."
license = "MIT OR Apache-2.0"
rust-version = "1.80"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = ["std"]
alloc = ["rarena-allocator/alloc", "crossbeam-skiplist/alloc"]
std = ["rarena-allocator/default", "crossbeam-skiplist/default", "bitflags/default"]

[dependencies]
bitflags = { version = "1", default-features = false }
rarena-allocator = { version = "0.2", default-features = false, features = ["memmap"] }
crossbeam-skiplist = { version = "0.1", default-features = false }
thiserror = "1"

[dev-dependencies]
criterion = "0.5"
tempfile = "3"

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
